dataction/urls.py
from os import name
from django.urls import path

from . import views

app_name = 'dataction'
urlpatterns = [
    path('', views.home, name='home'),
    path('submit/',views.submit,name='submit'),
    path('point_index/',views.point_index,name="point_index"),
    path('consigne/',views.consigne,name="consigne"),
    path('test/',views.test,name='test'),
    path('<int:point_id>/',views.point_detail,name="detail"),
    path('global_map/',views.global_map,name="global_map"),
]

dataction/models.py
import datetime

from django.db import models
from django.utils import timezone

''' modèle
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
'''

class pointGPS(models.Model):
    coord = models.CharField(max_length=100)
    lat = models.CharField(max_length=50)
    long = models.CharField(max_length=50)
    #éventullement mettre un char à la place de date
    shot_date = models.DateTimeField('photo date')
    clean_state = models.BooleanField(default=False)
    # pourcentage de certitude

    def __str__(self):
        return self.coord


        

dataction/views.py
from datetime import datetime
from django import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import context, loader
from django.template.base import Template
from django.urls import reverse
from object_detection.utils import visualization_utils as viz_utils

import os
import numpy as np
from six import BytesIO

import tensorflow as tf

import PIL.Image as pimg
import PIL.ExifTags

from .models import pointGPS

#'C:/Users/nil75/Desktop/prog/django/projet/dataction/inference_graph/saved_model'
detect_fn = tf.saved_model.load(os.path.abspath("inference_graph/saved_model"))

def home(request):
    return render(request,'home.html',{})

def submit(request):
    return render(request,'submit.html',{})

def point_index(request):
    point_list = pointGPS.objects.all()

    return render(request,'point_index.html',{"point_list":point_list})

def consigne(request):
    return render(request,"consigne.html")


#pour l'instant tout est dans test
def treatment(request):
    try:
        doc = request.POST['document']
    except:
        # Redisplay the question voting form.
        return HttpResponse("c'est rapé")

    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponse(type(doc))



def test(request):
    try:
        doc = request.POST['document']
    except:
        # Redisplay the question voting form.
        return render(request,'submit.html',{"error": "erreur loes de la soumission du form veuillez réesayer"})
   
    #changé ça
    #path = "C://Users//" + os.getlogin() + "//Pictures//" + doc
    path = os.path.abspath("image") +"/"+ doc

# chargement de l'image pour donné EXIF
    try:
        img = pimg.open(path)
    except:
        return render(request,'submit.html',{"error": "image non trouvé dans le répertoire " + path})

#récupération des donné EXIF et vérification
    exif_data = img._getexif()

    exif = None
    if(exif_data != None):
        exif = {
            PIL.ExifTags.TAGS[k]: v
            for k, v in img._getexif().items()
            if k in PIL.ExifTags.TAGS
        }
    else:
        return render(request,'submit.html',{"error": "l'image fournit ne contient pas de données exif est n'est donc pas recevable"})

    if(not "GPSInfo" in exif.keys()):
        return render(request,'submit.html',{"error": "l'image fournit ne contient pas de données GPS merci de vérifier que le paramètre tags de localisation de votre appareil photo de smartphone est bien activé, pour plus d'information reférez vous à la page instruction."})

#test via IA pour voir si déchet ou non

    img = load_image_into_numpy_array(path)
    input_tensor = np.expand_dims(img, 0)
    detections = detect_fn(input_tensor)

    score = detections['detection_scores'][0][0].numpy()


    category_index = {
        1: {'id': 1, 'name': 'Plastic'},
        2: {'id': 2, 'name': 'Not_Plastic'},
    }

    image_np_with_detections = img.copy()
    viz_utils.visualize_boxes_and_labels_on_image_array(
        image_np_with_detections,
        detections['detection_boxes'][0].numpy(),
        detections['detection_classes'][0].numpy().astype(np.int32),
        detections['detection_scores'][0].numpy(),
        category_index,
        use_normalized_coordinates=True,
        max_boxes_to_draw=200,
        min_score_thresh=.40,
        agnostic_mode=False)

    PIL_image = pimg.fromarray(np.uint8(image_np_with_detections)).convert('RGB')
    PIL_image.show()

    if (score < 0.50):
        erreur = "aucun déchets n'a été trouvé sur votre image s'il s'agit d'une erreur essayé de prendre la photo sous un angle différent. confidence=" + str(score)
        return render(request, 'submit.html', {"error": erreur})



 #ajout du point dans la bdd
    coord = EXIF_to_MDS(exif["GPSInfo"])
    lat, long = MDS_to_latlong(coord)

    date = exif["DateTimeOriginal"].split(":")
    date = datetime(int(date[0]),int(date[1]),int(date[2][0:2]),int(date[2][3:]),int(date[3]),int(date[4]))
    
    new_point = pointGPS(coord=coord,lat=lat,long=long,shot_date=date,clean_state=False)
    new_point.save()

#affichage de la page de détail du point ajouté
    return HttpResponseRedirect(reverse('dataction:detail',args=(new_point.id,)))


def point_detail(request,point_id):
    point = get_object_or_404(pointGPS, pk=point_id)

    return render(request,'detail.html', {'point': point,"coord_integration":coord_transform(point.coord)})

def global_map(request):
    point_list = pointGPS.objects.all()

    return render(request, 'global_map.html', {"point_list": point_list})
        

'''
liste des vue:
home : page d'accueil   ->tout les autres(navbar)
submit : soumettre image    -> point_detail(correspondant)
point_list : tout les point GPS -> point_detail & map
point_detail : le détail d'un point -> point_list & lien maps
map : carte de tout les points  -> à voir
'''
    



#déplacer pour propreté (à validé par les test)

def coord_transform(coord):
    coord_int = coord.replace("°","%C2%B0")
    coord_int =  coord_int.replace("\"","%22")
    coord_int = coord_int.replace(" ","%20")
    return coord_int

def MDS_to_latlong(conver):
    
    conver = conver.replace("\"", "//")
    conver = conver.replace("°", "//")
    conver = conver.replace("'", "//")
    conver = conver.replace("N", "//")
    conver = conver.replace("E", "//") 
    conver = conver.replace("////", "//") 
    conver = conver.split("//")
    
    conver = conver[:-1]
    
    final = []
    for elem in conver:
        if(elem == ''):
            conver.remove(elem)
        else: 
            elem = float(elem)
        print(type(elem))
        print(elem)
        final.append(elem)
    
    lat =  final[0]+((final[1]/60)+final[2])/60
    long = final[3]+((final[4]/60)+final[5])/60
    
    return (lat,long)

def EXIF_to_MDS(GPSInfo):
    coord = ""

    coord+= str(int(GPSInfo[2][0])) + "°"
    coord+= str(int(GPSInfo[2][1])) + "'"
    coord+= str(GPSInfo[2][2]) + "\"" + GPSInfo[1] + " "

    coord+= str(int(GPSInfo[4][0])) + "°"
    coord+= str(int(GPSInfo[4][1])) + "'"
    coord+= str(GPSInfo[4][2]) + "\"" + GPSInfo[3]

    print("https://www.google.fr/maps/place/" + coord)
    return coord

def load_image_into_numpy_array(path):
 
  img_data = tf.io.gfile.GFile(path, 'rb').read()
  image = pimg.open(BytesIO(img_data))
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

dataction/templates/consigne.html
<h1>consigne d'utilisation :</h1>

<h2>soumettre une image</h2>

<p>1. avant de prendre votre photo vous devez imperativement activer la géolocalisation sur votre appareil ainsi que l'option "Tags de localisation" dans les options de votre appareil photo
<!-- insérer une image -->

<p>2. pour soumettre votre image vous devez la placé dans le répertoire image de votre ordinateur puis la séléctioné via l'interface accessible depuis la page submit




dataction/templates/detail.html
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Dataction</title>
		{% load static %}
        <link rel="icon" href="{% static 'Logo_dataction.ico' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Crete+Round">
    </head>
    <body>
        <div id="app">
          <header id="main-image">
            <div class="wrapper">
              <h1 style="margin-top: 100px;" onclick="location.href='{% url 'dataction:home' %}';" style="cursor: pointer;">Dataction<span class="bleu">.</span></h1>
              <nav style="margin-top: 125px;">
                <a class="nav" href="{% url 'dataction:home' %}"> Accueil </a>
                <a class="nav" href='{% url "dataction:submit" %}'> Soumettre une image </a>
                <a class="nav" href='{% url "dataction:global_map" %}'> Carte des déchets </a>
                <a class="nav" href='{% url "dataction:point_index" %}'> Liste des points GPS </a>

              </nav>
            </div>
          </header>
          <div class="bar"></div>



    <div class="centre">
        <br>
        <a href="https://www.google.fr/maps/place/{{ point.coord }}"><h2>Points sur la map</h2></a><br>

        <div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q={{ coord_integration }}&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://fmovies2.org"></a><br><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style><a href="https://www.embedgooglemap.net">custom map for website</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div></div>

        </div>
        </div>

dataction/templates/global_map.html
<!DOCTYPE html>
<html>
  <head>
    <title>Add Map</title>
	<meta charset="utf-8">
	{% load static %}
    <link rel="icon" href="{% static 'Logo_dataction.ico' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Crete+Round">

    <style type="text/css">
      /* Set the size of the div element that contains the map */
      #map {
        height: 600px;
        /* The height is 400 pixels */
        width: 100%;
        /* The width is the width of the web page */
      }
    </style>
    <script>
      // Initialize and add the map
      function initMap() {

        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 4,
            center: { lat: {{ point_list.0.lat }}, lng: {{ point_list.0.long }} },
        });

        const svgMarkerRed = {
            path: "M10.453 14.016l6.563-6.609-1.406-1.406-5.156 5.203-2.063-2.109-1.406 1.406zM12 2.016q2.906 0 4.945 2.039t2.039 4.945q0 1.453-0.727 3.328t-1.758 3.516-2.039 3.070-1.711 2.273l-0.75 0.797q-0.281-0.328-0.75-0.867t-1.688-2.156-2.133-3.141-1.664-3.445-0.75-3.375q0-2.906 2.039-4.945t4.945-2.039z",
            fillColor: '#FF0000',
            fillOpacity: .6,
            anchor: new google.maps.Point(15,30),
            strokeWeight: 0,
            scale: 1
        };

        const svgMarkerBlue = {
            path: "M10.453 14.016l6.563-6.609-1.406-1.406-5.156 5.203-2.063-2.109-1.406 1.406zM12 2.016q2.906 0 4.945 2.039t2.039 4.945q0 1.453-0.727 3.328t-1.758 3.516-2.039 3.070-1.711 2.273l-0.75 0.797q-0.281-0.328-0.75-0.867t-1.688-2.156-2.133-3.141-1.664-3.445-0.75-3.375q0-2.906 2.039-4.945t4.945-2.039z",
            fillColor: '#0022ff',
            fillOpacity: .6,
            anchor: new google.maps.Point(15,30),
            strokeWeight: 0,
            scale: 1
        };

        {% for point in point_list %}

            {% if point.clean_state == True %}
                console.log("coucou")
                new google.maps.Marker({
                position: { lat: {{point.lat}}, lng: {{point.long}} },
                map: map,
                icon: svgMarkerBlue,
            });

            {% else %}
                console.log("pas coucou")
                new google.maps.Marker({
                position: { lat: {{point.lat}}, lng: {{point.long}} },
                map: map,
                icon: svgMarkerRed,
            });
            {% endif %}
        {% endfor %}

      }
    </script>
  </head>
  <body>
  
  <div id="app">
          <header id="main-image">
            <div class="wrapper">
              <h1 style="margin-top: 100px;" onclick="location.href='{% url 'dataction:home' %}';" style="cursor: pointer;">Dataction<span class="bleu">.</span></h1>
              <nav style="margin-top: 125px;">
                <a class="nav" href="{% url 'dataction:home' %}"> Accueil </a>
                <a class="nav" href='{% url "dataction:submit" %}'> Soumettre une image </a>
                <a class="nav" href='{% url "dataction:global_map" %}'> Carte des déchets </a>
                <a class="nav" href='{% url "dataction:point_index" %}'> Liste des points GPS </a>

              </nav>
            </div>
          </header>
          <div class="bar"></div>

  <h3 class="h3">My Google Maps Demo</h3>
    <!--The div element for the map -->
    <div id="map"></div>
    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCoK3ADy19VBqDadAOVkot5DssFoEMHMq8&callback=initMap&libraries=&v=weekly"
      async
    ></script>
      <p style="margin-bottom: 100px"></p>
  </body>
</html>

dataction/templates/home.html

<!doctype>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Dataction</title>
		{% load static %}
        <link rel="icon" href="{% static 'Logo_dataction.ico' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Crete+Round">
    </head>
    <body>
    <div id="app">
        <header id="main-image">
            <div class="wrapper">
                <h1 style="margin-top: 100px;" onclick="location.href='{% url 'dataction:home' %}';" style="cursor: pointer;">Dataction<span class="bleu">.</span></h1>
                <nav style="margin-top: 125px;">
                    <a class="nav" href="{% url 'dataction:home' %}"> Accueil </a>
                    <a class="nav" href='{% url "dataction:submit" %}'> Soumettre une image </a>
                    <a class="nav" href='{% url "dataction:global_map" %}'> Carte des déchets </a>
                    <a class="nav" href='{% url "dataction:point_index" %}'> Liste des points GPS </a>

                </nav>
            </div>
        </header>
        <div class="bar"></div>
        <div id="accueil-image">
            <br><br><br><br><br><br>
            <div class="presentation">
                <h3 class="h3">Quel problème actuel ?</h3>
                <br>
                <p class="p">Depuis plusieurs années, la quantité de déchets plastiques ne cesse d’augmenter et de polluer notre environnement.<br>C’est pourquoi notre équipe a décidé de se mettre à l’épreuve afin de pouvoir remédier à ce problème aux enjeux non négligeables.</p>
                <br>
                <h3 class="h3">Qui sommes-nous ?</h3>
                <br>
                <p class="p">Nous sommes une équipe de l’entreprise DATACTION composée de 6 étudiants en troisième année d’école d’ingénieur EFREI Paris<br> BEKHOUCHE Abdel Hak, BOUDIN Armand, CAILLEUX Nil, GWET Karis, HANANIA Mathieu et ILOO LIANDJA Moïse.</p>
                <br>
                <h3 class="h3">Que proposons-nous ?</h3>
                <p class="p">Notre objectif est de concevoir une application visant à détecter et cartographier les déchets plastiques afin d’agir pour le bien de notre environnement.</p>
            </div>
        </div>
    </div>
    </body>
</html>

dataction/templates/point_index.html
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Dataction</title>
		{% load static %}
        <link rel="icon" href="{% static 'Logo_dataction.ico' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Crete+Round">
    </head>
    <body>
        <div id="app">
          <header id="main-image">
            <div class="wrapper">
              <h1 style="margin-top: 100px;" onclick="location.href='{% url 'dataction:home' %}';" style="cursor: pointer;">Dataction<span class="bleu">.</span></h1>
              <nav style="margin-top: 125px;">
                <a class="nav" href="{% url 'dataction:home' %}"> Accueil </a>
                <a class="nav" href='{% url "dataction:submit" %}'> Soumettre une image </a>
                <a class="nav" href='{% url "dataction:global_map" %}'> Carte des déchets </a>
                <a class="nav" href='{% url "dataction:point_index" %}'> Liste des points GPS </a>

              </nav>
            </div>
          </header>
          <div class="bar"></div>




{% if point_list %}
    <table>
        <thead>
            <tr>
                <th><h3> Cordonnées GPS des déchets</h3></th>
            </tr>
        </thead>
        <tbody>
        {% for point in point_list %}
            <tr>
                <td><a href="{% url 'dataction:detail' point.id %}">{{ point.coord }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No point are available.</p>
{% endif %}

dataction/templates/submit.html
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Dataction</title>
		{% load static %}
        <link rel="icon" href="{% static 'Logo_dataction.ico' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Crete+Round">
    </head>
    <body>
        <div id="app">
          <header id="main-image">
            <div class="wrapper">
              <h1 style="margin-top: 100px;" onclick="location.href='{% url 'dataction:home' %}';" style="cursor: pointer;">Dataction<span class="bleu">.</span></h1>
              <nav style="margin-top: 125px;">
                <a class="nav" href="{% url 'dataction:home' %}"> Accueil </a>
                <a class="nav" href='{% url "dataction:submit" %}'> Soumettre une image </a>
                <a class="nav" href='{% url "dataction:global_map" %}'> Carte des déchets </a>
                <a class="nav" href='{% url "dataction:point_index" %}'> Liste des points GPS </a>

              </nav>
            </div>
          </header>
          <div class="bar"></div>

{% if error %}
<h3>{{error}}</h3>
<br>
{% endif %}


<h2 class="h2">Choix de l'image :</h2>
  <form class="formulaire" method="post", action="{% url 'dataction:test' %}">
    {% csrf_token %}
    <input class="button1" style="font-family: 'Crete Round', serif;" type="file" id="document" name="document",accept=".png, .jpg, .jpeg">
      <br>
    <input class="button" style="font-family: 'Crete Round', serif;" type="submit" value="Valider">
  </form>